### PR TITLE
Updates scripts to use new per project folder structure

### LINKED ISSUE #38: Update documentation and scripts to reflect new per project folder structure
- [ ] run1.sh
- [ ] run4.sh

### PR DESCRIPTION
**Pull request by palanik1**
Fixes #38

### CODE REVIEW

**Review by sdsen — DISMISSED** [review]
lgtm

**Comment by dushyantbehl** [comment]
lgtm as well.

**Review by dushyantbehl — CHANGES_REQUESTED** [review]
@palanik1 can you update the commit and add a sign.

**Review by dushyantbehl — APPROVED** [review]
Changes look good.

**Comment by sdsen** [comment]
@palanik1 all commits need to be signed. Maybe squash and push ?

**Review by dushyantbehl — APPROVED** [review]
Look similar. Good to go.

**Pull request merged**
